//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gosafe_back.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempLink
    {
        public string TempLinkId { get; set; }
        public int JourneyJourneyId { get; set; }
        public string UserProfileId { get; set; }
    
        public virtual Journey Journey { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
